version: "3.9"
services:
  builder:
    container_name: aosp_builder
    hostname: aosp_builder
    build: ./build
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/gitconfig:/root/.gitconfig:ro
      - /opt/aosp-build/aosp:/aosp:rw
      - /opt/aosp-build/ccache:/ccache:rw
      - /opt/aosp-build/aosp-home:/home/aosp/:rw
      - ./:/script/:rw
